[package]
name = "framework"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[dependencies]
cpal = "0.13.1"
image = "0.23.12"
num-traits = "0.2.14"
pixels = "0.2.0"
rayon = "1.5.0"
vek = "0.12.1"
winit = "0.23.0"
winit_input_helper = "0.8.0"
